version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "3001:5432"
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
  server:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - "postgres"
    depends_on:
      - postgres
